name: Python Basic App

# event
on:
  push:
    branches:
       - "main"

# 
jobs:
  custom_build:
    

    runs-on: ubuntu-latest
#checkout :- github ke andar code ayga nahi 
    steps:
      - uses: actions/checkout@v3
# name means :- display as heading
      - name: Set up Python 3 
        uses: actions/setup-python@v3
        with: # with use for python version
            python-version: 3.12